### ISSUE TITLE
Error when searching for images or uploading images

### ISSUE THREAD

**Issue by emilyhorsman** [littleweaver/littleweaverweb.com#100]
**Steps to reproduce:**

1. Add a Captioned Image block to a StreamField
2. Open the ImageChooserPanel
3. Attempt to search for an image

**Expected Behaviour:**

Images appear.

**Actual Behaviour:**

No images appear.

Stack trace from `/var/log/django/django.log`
```
[2017-08-11 22:51:04,787 ERROR] Internal Server Error: /admin/images/chooser/
Traceback (most recent call last):
  File "/var/www/env/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/var/www/env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/var/www/env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/var/www/env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/www/env/local/lib/python2.7/site-packages/newrelic-2.54.0.41/newrelic/hooks/framework_django.py", line 499, in wrapper
    return wrapped(*args, **kwargs)
  File "/var/www/env/local/lib/python2.7/site-packages/django/views/decorators/cache.py", line 43, in _cache_controlled
    response = viewfunc(request, *args, **kw)
  File "/var/www/env/local/lib/python2.7/site-packages/wagtail/wagtailadmin/decorators.py", line 27, in decorated_view
    return view_func(request, *args, **kwargs)
  File "/var/www/env/local/lib/python2.7/site-packages/wagtail/wagtailimages/views/chooser.py", line 88, in chooser
    'will_select_format': request.GET.get('select_format')
  File "/var/www/env/local/lib/python2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/var/www/env/local/lib/python2.7/site-packages/django/template/loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "/var/www/env/local/lib/python2.7/site-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/var/www/env/local/lib/python2.7/site-packages/django/template/base.py", line 207, in render
    return self._render(context)
  File "/var/www/env/local/lib/python2.7/site-packages/newrelic-2.54.0.41/newrelic/api/function_trace.py", line 98, in dynamic_wrapper
    return wrapped(*args, **kwargs)
  File "/var/www/env/local/lib/python2.7/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/var/www/env/local/lib/python2.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/var/www/env/local/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/var/www/env/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 322, in render
    return nodelist.render(context)
  File "/var/www/env/local/lib/python2.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/var/www/env/local/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/var/www/env/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 216, in render
    nodelist.append(node.render_annotated(context))
  File "/var/www/env/local/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/var/www/env/local/lib/python2.7/site-packages/wagtail/wagtailimages/templatetags/wagtailimages_tags.py", line 88, in render
    rendition = get_rendition_or_not_found(image, self.filter)
  File "/var/www/env/local/lib/python2.7/site-packages/wagtail/wagtailimages/shortcuts.py", line 16, in get_rendition_or_not_found
    return image.get_rendition(specs)
  File "/var/www/env/local/lib/python2.7/site-packages/wagtail/wagtailimages/models.py", line 271, in get_rendition
    generated_image = filter.run(self, BytesIO())
  File "/var/www/env/local/lib/python2.7/site-packages/wagtail/wagtailimages/models.py", line 404, in run
    return willow.save_as_jpeg(output, quality=quality, progressive=True, optimize=True)
TypeError: save_as_jpeg() got an unexpected keyword argument 'progressive'
```

**Comment by emilyhorsman** [comment]
This was likely caused by upgrading Wagtail, we [needed to upgrade Willow](https://github.com/wagtail/wagtail/issues/3105) at the same time.
